### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by guthrey1** [kipoi/examples#3]
I followed these instructions: 
![image](https://user-images.githubusercontent.com/53881763/63060572-a6073800-bec0-11e9-89ef-933f239c4b76.png)  

but when I reach the actual kipoi predict step it says command not found. I previously ran multiple kipoi predict jobs simultaneously on this enviornment and I am wondering why now this command cannot be found.

**Comment by Avsecz** [comment]
Can you run `which kipoi`, `which gkmpredict` and `echo $PATH` in the `kipoi-lsgkm-SVM` environment?

Note that if you run the first command (`kipoi env create`) you don't have to run the second one (`kipoi env install`).

**Comment by guthrey1** [comment]
![image](https://user-images.githubusercontent.com/53881763/63185381-e59c6400-c027-11e9-9516-b9fade131d2f.png)
![image](https://user-images.githubusercontent.com/53881763/63185429-049af600-c028-11e9-8322-b62c8e9b80a6.png)
Is kipoi in the wrong place?

**Comment by Avsecz** [comment]
Hm. Yes. Kipoi doesn't seem to be installed. Could you paste the exact commands you used to reach that environment? Try installing kipoi explicitly using `pip install kipoi` to the lsgkm-SVM environment and then run the same `which` commands in a new terminal (after running source activate kipoi lsgkm-SVM)

**Comment by guthrey1** [comment]
Thank you that worked



Sent from Mail for Windows 10

**Comment by Avsecz** [comment]
can we close this issue?
